version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:CpyZZyCN4VB4IK/YYQhXreDKhPME5cZVNYuLtay/wGA=
      APP_DEBUG: 'true'
      APP_TIMEZONE: UTC
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: codifica_jovens
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: codifica_jovens
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
